services:
  vector-db:
    image: qdrant/qdrant:v1.7.0
    container_name: qdrant-server
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC 포트
    volumes:
      - ./data/qdrant:/qdrant/storage
      - ./vector-db/config/qdrant.yaml:/qdrant/config/production.yaml
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c 'cat < /dev/null > /dev/tcp/localhost/6333'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - rag-network

  embedding-server:
    build: ./embedding-server
    container_name: embedding-server
    ports:
      - "8001:8001"
    volumes:
      - ./embedding-server:/app
      - ./models:/app/models:ro
      - embedding-cache:/app/cache
    environment:
      - MODEL_NAME=sentence-transformers/all-MiniLM-L6-v2
      - HOST=0.0.0.0
      - PORT=8001
    depends_on:
      vector-db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c 'cat < /dev/null > /dev/tcp/localhost/8001'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - rag-network

  llm-server:
    build: ./llm-server
    container_name: llm-server
    ports:
      - "8002:8002"
    volumes:
      - ./llm-server:/app
    environment:
      - MODEL_NAME=gpt-4o-mini
      - HOST=0.0.0.0
      - PORT=8002
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c 'cat < /dev/null > /dev/tcp/localhost/8002'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - rag-network

  rag-server:
    build: ./rag-server
    container_name: rag-server
    ports:
      - "8000:8000"
    volumes:
      - ./rag-server:/app
      - ./test-codebase:/test-codebase:ro
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - EMBEDDING_SERVER_URL=http://embedding-server:8001
      - LLM_SERVER_URL=http://llm-server:8002
      - VECTOR_DB_URL=http://vector-db:6333
    depends_on:
      embedding-server:
        condition: service_healthy
      llm-server:
        condition: service_healthy
      vector-db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c 'cat < /dev/null > /dev/tcp/localhost/8000'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    networks:
      - rag-network

  postgres:
    image: postgres:13
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=evaluation_db
      - POSTGRES_USER=evaluation_user
      - POSTGRES_PASSWORD=evaluation_pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U evaluation_user -d evaluation_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - rag-network

  evaluation-server:
    build: ./evaluation-server
    container_name: evaluation-server
    ports:
      - "8003:8003"
    volumes:
      - ./evaluation-server:/app
      - ./evaluation-server/datasets:/app/datasets
    environment:
      - HOST=0.0.0.0
      - PORT=8003
      - DATABASE_URL=postgresql://evaluation_user:evaluation_pass@postgres-db:5432/evaluation_db
      - DATASETS_PATH=./datasets
      - EMBEDDING_SERVER_URL=http://embedding-server:8001
      - LLM_SERVER_URL=http://llm-server:8002
      - RAG_SERVER_URL=http://rag-server:8000
      - VECTOR_DB_URL=http://vector-db:6333
      - LOG_LEVEL=INFO
      - API_V1_PREFIX=/api/v1
      - SECRET_KEY=your-secret-key-change-this-in-production
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  qdrant-data:
  embedding-cache:
  postgres-data: 