service:
  max_request_size_mb: 32
  max_workers: 0
  enable_cors: true

storage:
  storage_path: ./storage
  snapshots_path: ./snapshots
  temp_path: ./temp

log_level: INFO

cluster:
  enabled: false

telemetry_disabled: true 